name: almasjid
description: "A Prayer and qibla application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.5+11

environment:
  sdk: ^3.6.1

dependencies:
  adhan: ^2.0.0+1
  arabic_justified_text: ^1.0.2
  archive: ^4.0.7
  awesome_notifications: ^0.10.1
  background_fetch: ^1.5.0
  badges: ^3.1.2
  bot_toast: ^4.1.3
  bubble_lens: ^2.0.0
  compassx: ^1.0.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drawing_animation:
    git:
      ref: master
      url: https://github.com/alheekmahlib/drawing_animation.git
  either_dart: ^1.0.0
  floating_menu_expendable: ^1.0.0
  floaty_nav_bar: #^1.0.2
    git:
      ref: main
      url: https://github.com/alheekmahlib/floaty_nav_bar.git
  flutter:
    sdk: flutter
  flutter_app_info: ^3.0.3
  flutter_cache_manager: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_native_splash: ^2.4.7
  flutter_rounded_progress_bar: ^0.3.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  gap: ^3.0.1
  gauge_indicator: ^0.4.3
  geolocator: ^14.0.2
  get: ^4.7.3
  get_it: ^9.2.0
  get_storage: ^2.1.1
  google_huawei_availability:
    git:
      ref: dev
      url: https://github.com/alheekmahlib/google_huawei_availability.git
  hijri_date: ^1.0.0
  home_widget: ^0.9.0
  horizontal_week_calendar:
    git:
      ref: main
      url: https://github.com/alheekmahlib/horizontal_week_calendar.git
  huawei_location: ^6.16.0+300
  huawei_site: ^6.5.1+303
  intl: ^0.20.2
  just_audio: ^0.10.5
  latlong2: ^0.9.1
  lottie: ^3.3.2
  nominatim_geocoding: ^0.0.6
  package_rename: ^1.10.1
  path: ^1.9.1
  path_provider: ^2.1.5
  rate_my_app: ^2.3.2
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  slide_countdown: ^2.0.2
  sliding_panel_kit: ^0.3.0
  smooth_page_indicator: ^2.0.1
  solar_icons: ^0.0.5
  square_percent_indicater: ^0.1.0
  timezone: ^0.10.1
  turf: ^0.0.10
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#001A23"
  color_dark: "#001A23"
  image: assets/images/aqim_icon_with_stroke.png
  image_dark: assets/images/aqim_icon_with_stroke.png
  # flutter_lints: true
  android_12:
    image: assets/images/aqim_icon_with_stroke.png
    icon_background_color: "#001A23"
    image_dark: assets/images/aqim_icon_with_stroke.png
    icon_background_color_dark: "#001A23"

package_rename_config:
  android:
    app_name: أقم - مكتبة الحكمة
    package_name: com.alheekmah.aqimApp
  ios:
    app_name: أقم - مكتبة الحكمة
    package_name: com.alheekmah.aqimApp
  macos:
    app_name: أقم - مكتبة الحكمة
    package_name: com.alheekmah.aqimApp
  windows:
    app_name: أقم - مكتبة الحكمة
  # flutter_lints: ^5.0.0
flutter_assets:
  # assets_path: assets/lottie/
  assets_path: assets/svg/
  output_path: lib/core/utils/constants/
  # filename: lottie_constants.dart
  filename: svg_constants.dart
  field_prefix: null
  class_name: SvgPath

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/svg/qibla/
    - assets/svg/logo/
    - assets/svg/home/
    - assets/svg/prayer/
    - assets/svg/theme/
    - assets/svg/share/
    - assets/svg/ramadan/
    - assets/images/
    - assets/svg/hijri/
    - assets/json/
    - assets/lottie/
    - assets/locales/
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 900
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
